(define (problem make-egg)
   (:domain do-egg)
   (:objects e5 e4 e3 e2 e1 o2 o1 d3 d2 d1 f2 f1 )

   (:init (eggs e5)
          (eggs e4)
          (eggs e3)
          (eggs e2)
          (eggs e1)
          (oil o2)
          (oil o1)
          (dish d3)
          (dish d2)
          (dish d1)
          (frying-pan f2)
          (frying-pan f1)
          (stove-on))

    (:goal (and (fried-egg)
                (eggOnDish)
                (stove-on)
    ))
)